server:
  port: 80

spring:
  application:
    name: order
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    register-with-eureka: false # 不注册进eureka服务中心
    service-url:
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    anthea.camellia.service.OrderService: info
